FROM python:3.8-buster

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt-get -y update
RUN apt-get install -y google-chrome-stable

COPY .env .
COPY requirements.txt .
COPY main.py .

RUN pip install --upgrade pip

RUN pip install -r requirements.txt
# RUN pip install python-dotenv

# #RUN pip install pipenv
# #RUN pipenv install --skip-lock --system --dev

CMD ["main.py"]
ENTRYPOINT ["python"]
