FROM openshift/jenkins-slave-base-centos7


# #### Python Selenium #### #

USER root

RUN yum install -y python3 python3-pip
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
RUN yum localinstall -y google-chrome-stable_current_x86_64.rpm

COPY requirements.txt /
COPY main.py /

RUN pip3 install --upgrade pip

RUN pip3 install -r /requirements.txt

RUN chmod 755 /usr/local/lib/python3.6/site-packages/chromedriver_binary/chromedriver

# NOTE for debug
# ENTRYPOINT ["bash"]

# #### #### #### #### #
